// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvD7P5hLR8I7WJju048RX4Ei_IhkCQLE',
    appId: '1:86511273436:web:1ed190eca0534b94103b19',
    messagingSenderId: '86511273436',
    projectId: 'felix-chatapp',
    authDomain: 'felix-chatapp.firebaseapp.com',
    storageBucket: 'felix-chatapp.firebasestorage.app',
    measurementId: 'G-Y1DMRPX0B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCct9pSlSa7WnQW3N-P48jCJ5s5p6KBWTk',
    appId: '1:86511273436:android:1e13c027affefe55103b19',
    messagingSenderId: '86511273436',
    projectId: 'felix-chatapp',
    storageBucket: 'felix-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8mqB6fTa0Cubcs1JQ_L5DHFQ1TGzB2go',
    appId: '1:86511273436:ios:b33520e02e541159103b19',
    messagingSenderId: '86511273436',
    projectId: 'felix-chatapp',
    storageBucket: 'felix-chatapp.firebasestorage.app',
    iosBundleId: 'com.mychatapp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8mqB6fTa0Cubcs1JQ_L5DHFQ1TGzB2go',
    appId: '1:86511273436:ios:b33520e02e541159103b19',
    messagingSenderId: '86511273436',
    projectId: 'felix-chatapp',
    storageBucket: 'felix-chatapp.firebasestorage.app',
    iosBundleId: 'com.mychatapp.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqvD7P5hLR8I7WJju048RX4Ei_IhkCQLE',
    appId: '1:86511273436:web:2175b7b896463963103b19',
    messagingSenderId: '86511273436',
    projectId: 'felix-chatapp',
    authDomain: 'felix-chatapp.firebaseapp.com',
    storageBucket: 'felix-chatapp.firebasestorage.app',
    measurementId: 'G-Q2PDK3T75P',
  );
}
